require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'config/**/*.rb'
    - 'db/**/*.rb'
    - 'spec/*_helper.rb'
    - 'config.ru'
    - 'Rakefile'

Style/SymbolProc:
  Exclude:
    - 'db/**/*.rb'
Style/Documentation:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - 'spec/factories/**.rb'
