services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: rails_user
      MYSQL_PASSWORD: password
